src/Shakyamouni/AdminBundle/Entity/NewsletterArticle.php
<?php

namespace Shakyamouni\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * NewsletterArticle
 *
 * @ORM\Table(name="newsletter_article")
 * @ORM\Entity(repositoryClass="Shakyamouni\AdminBundle\Repository\NewsletterArticleRepository")
 */
class NewsletterArticle
{
    
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
     /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank()
     */
    private $picture;

    /**
     * @Assert\File(maxSize="2M")
     */
    public $file;

    /**
     * @var string
     *
     * @ORM\Column(name="body", type="text", nullable=true)
     */
    private $body;

    /**
     * @var string
     *
     * @ORM\Column(name="is_reservation_link", type="boolean", nullable=true)
     */
    private $isReservationLink;

    /**
     * @var integer $position
     *
     * @ORM\Column(name="position", type="integer", nullable=false)
     * @Assert\NotBlank()
     */
    private $position;
    
     /**
     * @ORM\ManyToOne(targetEntity="Shakyamouni\SiteBundle\Entity\Event", inversedBy="newsletterarticles")
     * @ORM\JoinColumn(name="event_id", referencedColumnName="id", nullable=true, onDelete="SET NULL")
     */
    private $event;
    
     /**
     * @ORM\ManyToOne(targetEntity="Shakyamouni\SiteBundle\Entity\ArticleEvent", inversedBy="newsletterarticles")
     * @ORM\JoinColumn(name="articleevent_id", referencedColumnName="id", nullable=true, onDelete="SET NULL")
     */
    private $articleevent;
    
     /**
     * @ORM\ManyToOne(targetEntity="Shakyamouni\MenuBundle\Entity\SubCategory", inversedBy="newsletterarticles")
     * @ORM\JoinColumn(name="subcategory_id", referencedColumnName="id", nullable=true, onDelete="SET NULL")
     */
    private $subCategory;
    
    /**
     * @ORM\ManyToOne(targetEntity="Shakyamouni\AdminBundle\Entity\Newsletter", inversedBy="newsletterarticles")
     * @ORM\JoinColumn(name="newsletter_id", referencedColumnName="id", nullable=true, onDelete="SET NULL")
     */
    private $newsletter;
    
    /**
     * @ORM\ManyToOne(targetEntity="Shakyamouni\SiteBundle\Entity\Article", inversedBy="newsletterarticles")
     * @ORM\JoinColumn(name="article_id", referencedColumnName="id", nullable=true, onDelete="SET NULL")
     */
    private $articleLie;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
    
    public function __toString()
    {
        return $this->title;
    }
    
    /**
     * Set createdAt
     *
     * @param datetime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Get createdAt
     *
     * @return datetime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param datetime $updatedAt
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Get updatedAt
     *
     * @return datetime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set picture
     *
     * @param string $picture
     * @return NewsletterArticle
     */
    public function setPicture($picture)
    {
        $this->picture = $picture;
    
        return $this;
    }

    /**
     * Get picture
     *
     * @return string 
     */
    public function getPicture()
    {
        return $this->picture;
    }

    /**
     * Set body
     *
     * @param string $body
     * @return NewsletterArticle
     */
    public function setBody($body)
    {
        $this->body = $body;
    
        return $this;
    }

    /**
     * Get body
     *
     * @return string 
     */
    public function getBody()
    {
        return $this->body;
    }
    
     /**
     * Set position
     *
     * @param integer $position
     */
    public function setPosition($position)
    {
        $this->position = $position;
    }

    /**
     * Get position
     *
     * @return integer 
     */
    public function getPosition()
    {
        return $this->position;
    }
    
      /**
     * Set event
     *
     * @param \Shakyamouni\SiteBundle\Entity\Event $event
     * @return NewsletterArticle
     */
    public function setEvent(\Shakyamouni\SiteBundle\Entity\Event $event = null)
    {
        $this->event = $event;

        return $this;
    }

    /**
     * Get event
     *
     * @return \Shakyamouni\SiteBundle\Entity\Event 
     */
    public function getEvent()
    {
        return $this->event;
    }
    
    /**
     * Set articleevent
     *
     * @param \Shakyamouni\SiteBundle\Entity\ArticleEvent $articleevent
     * @return NewsletterArticle
     */
    public function setArticleevent(\Shakyamouni\SiteBundle\Entity\ArticleEvent $articleevent = null)
    {
        $this->articleevent = $articleevent;

        return $this;
    }

    /**
     * Get articleevent
     *
     * @return \Shakyamouni\SiteBundle\Entity\ArticleEvent 
     */
    public function getArticleevent()
    {
        return $this->articleevent;
    }
    
    public function getWebPath()
    {
        return null === $this->picture ? null : $this->getUploadDir() . '/' . $this->picture;
    }

    protected function getUploadRootDir()
    {
        // le chemin absolu du répertoire dans lequel sauvegarder les photos de profil
        return __DIR__ . '/../../../../web/' . $this->getUploadDir();
    }

    protected function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw when displaying uploaded doc/image in the view.
        return 'uploads/newsletter';
    }

    public function uploadProfilePicture()
    {
        // Nous utilisons le nom de fichier original, donc il est dans la pratique
        // nécessaire de le nettoyer pour éviter les problèmes de sécurité
        // move copie le fichier présent chez le client dans le répertoire indiqué.
        $securedFileName = sha1(uniqid(mt_rand(), true). $this->file->getClientOriginalName() * microtime(false)).'.'.$this->file->guessExtension();
        
        $this->file->move($this->getUploadRootDir(), $securedFileName);

        // On sauvegarde le nom de fichier
        $this->picture = $securedFileName;

        // La propriété file ne servira plus
        $this->file = null;
    }

    /**
     * Set newsletter
     *
     * @param \Shakyamouni\AdminBundle\Entity\Newsletter $newsletter
     * @return NewsletterArticle
     */
    public function setNewsletter(\Shakyamouni\AdminBundle\Entity\Newsletter $newsletter)
    {
        $this->newsletter = $newsletter;
    
        return $this;
    }

    /**
     * Get newsletter
     *
     * @return \Shakyamouni\AdminBundle\Entity\Newsletter 
     */
    public function getNewsletter()
    {
        return $this->newsletter;
    }

    /**
     * Set isReservationLink
     *
     * @param boolean $isReservationLink
     * @return NewsletterArticle
     */
    public function setIsReservationLink($isReservationLink)
    {
        $this->isReservationLink = $isReservationLink;
    
        return $this;
    }

    /**
     * Get isReservationLink
     *
     * @return boolean 
     */
    public function getIsReservationLink()
    {
        return $this->isReservationLink;
    }

    /**
     * Set subCategory
     *
     * @param \Shakyamouni\MenuBundle\Entity\SubCategory $subCategory
     * @return NewsletterArticle
     */
    public function setSubCategory(\Shakyamouni\MenuBundle\Entity\SubCategory $subCategory = null)
    {
        $this->subCategory = $subCategory;
    
        return $this;
    }

    /**
     * Get subCategory
     *
     * @return \Shakyamouni\MenuBundle\Entity\SubCategory 
     */
    public function getSubcategory()
    {
        return $this->subCategory;
    }

    /**
     * Set articleLie
     *
     * @param \Shakyamouni\SiteBundle\Entity\Article $articleLie
     * @return NewsletterArticle
     */
    public function setArticleLie(\Shakyamouni\SiteBundle\Entity\Article $articleLie = null)
    {
        $this->articleLie = $articleLie;
    
        return $this;
    }

    /**
     * Get articleLie
     *
     * @return \Shakyamouni\SiteBundle\Entity\Article 
     */
    public function getArticleLie()
    {
        return $this->articleLie;
    }
}

src/Shakyamouni/AdminBundle/Controller/ArticleAdminController.php
<?php

namespace Shakyamouni\AdminBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Shakyamouni\SiteBundle\Entity\Article;
use Shakyamouni\SiteBundle\Form\ArticleType;

/**
 * Article controller.
 *
 * @Route("/article_admin")
 */
class ArticleAdminController extends Controller {

    /**
     * Lists all Article entities.
     *
     * @Template("ShakyamouniAdminBundle:ArticleAdmin:list.html.twig")
     */
    public function listAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('ShakyamouniMenuBundle:SubCategory')->getSubCategoriesWithArticles();

        return array(
            'entities' => $entities,
        );
    }

    public function articlesBySubCategoryAction($subcategory_slug)
    {
        $articles = $this->getDoctrine()
                ->getRepository('ShakyamouniSiteBundle:Article')
                ->getArticlesBySubCategory($subcategory_slug);

        return $this->container->get('templating')
                        ->renderResponse('ShakyamouniAdminBundle:ArticleAdmin:articlesBySubCategory.html.twig', array(
                            'articles' => $articles,
                                )
        );
    }

    /**
     * Lists all Article entities.
     *
     * @Route("/list", name="article_admin")
     * @Template("ShakyamouniAdminBundle:ArticleAdmin:index.html.twig")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('ShakyamouniSiteBundle:Article')->findAllBySubCategoryASCAndTitleASC();

        return array(
            'entities' => $entities,
        );
    }

    /**
     * Finds and displays a Article entity.
     *
     * @Route("/{id}/show", name="article_admin_show")
     * @Template("ShakyamouniAdminBundle:ArticleAdmin:show.html.twig")
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('ShakyamouniSiteBundle:Article')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Article entity.');
        }

        return array(
            'article' => $entity,
        );
    }

    /**
     * Displays a form to create a new Article entity.
     *
     * @Route("/new", name="article_admin_new")
     * @Template("ShakyamouniAdminBundle:ArticleAdmin:new.html.twig")
     */
    public function newAction()
    {
        $entity = new Article();
        $form = $this->createForm(new ArticleType(), $entity);

        return array(
            'entity' => $entity,
            'form' => $form->createView(),
        );
    }

    /**
     * Creates a new Article entity.
     *
     * @Route("/create", name="article_admin_create")
     * @Method("POST")
     * @Template("ShakyamouniAdminBundle:ArticleAdmin:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity = new Article();
        $form = $this->createForm(new ArticleType(), $entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();

         //   $isVisibleValueForm = $form->getData()->getIsVisible();
            $isPictureValueForm = $form->getData()->getIsPicture();
            $fileValueForm = $form->getData()->file;

            if ($isPictureValueForm && !empty($fileValueForm)) {
           // if ('yes' === $isPictureValueForm && !empty($fileValueForm)) {
                $entity->uploadProfilePicture();
//            } elseif ('yes' === $isPictureValueForm && empty($fileValueForm)) {
            } elseif ($isPictureValueForm && empty($fileValueForm)) {
                $this->get('session')->getFlashBag()->add('notice', 'Vous avez indiqué avoir une image principale mais n\'en avez pas sélectionnée.');
                return array(
                    'entity' => $entity,
                    'form' => $form->createView(),
                );
            } else {
                $entity->setPicture(NULL);
            }
            
//            if ('yes' === $isVisibleValueForm){
//                $entity->setIsVisible(true);
//            }
//            else {
//                $entity->setIsVisible(false);
//            }

            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('article_admin_show', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form' => $form->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Article entity.
     *
     * @Route("/{id}/edit", name="article_admin_edit")
     * @Template("ShakyamouniAdminBundle:ArticleAdmin:edit.html.twig")
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('ShakyamouniSiteBundle:Article')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Article entity.');
        }

        $editForm = $this->createForm(new ArticleType(), $entity);

        return array(
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
        );
    }

    /**
     * Edits an existing Article entity.
     *
     * @Route("/{id}/update", name="article_admin_update")
     * @Method("POST")
     * @Template("ShakyamouniAdminBundle:ArticleAdmin:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('ShakyamouniSiteBundle:Article')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Article entity.');
        }

        $editForm = $this->createForm(new ArticleType(), $entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {

   //         $isVisibleValueForm = $editForm->getData()->getIsVisible();
            $isPictureValueForm = $editForm->getData()->getIsPicture();
            $fileValueForm = $editForm->getData()->file;

//            if ('yes' === $isPictureValueForm && NULL !== $entity->getPicture() && !empty($fileValueForm)) {
            if ($isPictureValueForm && NULL !== $entity->getPicture() && !empty($fileValueForm)) {
                $entity->uploadProfilePicture();
//            } elseif ('yes' === $isPictureValueForm && NULL !== $entity->getPicture() && empty($fileValueForm)) {
            } elseif ($isPictureValueForm && NULL !== $entity->getPicture() && empty($fileValueForm)) {
                $entity->setPicture($entity->getPicture());
//            } elseif ('yes' === $isPictureValueForm && NULL === $entity->getPicture() && !empty($fileValueForm)) {
            } elseif ($isPictureValueForm && NULL === $entity->getPicture() && !empty($fileValueForm)) {
                $entity->uploadProfilePicture();
//            } elseif ('yes' === $isPictureValueForm && NULL === $entity->getPicture() && empty($fileValueForm)) {
            } elseif ($isPictureValueForm && NULL === $entity->getPicture() && empty($fileValueForm)) {
                $this->get('session')->getFlashBag()->add('notice', 'Vous avez indiqué avoir une image principale mais n\'en avez pas sélectionnée.');
                return $this->redirect($this->generateUrl('article_admin_edit', array('id' => $id)));
            } else {
                $entity->setPicture(NULL);
            }
            
//            if ('yes' === $isVisibleValueForm){
//                $entity->setIsVisible(true);
//            }
//            else {
//                $entity->setIsVisible(false);
//            }

            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('article_admin_show', array('id' => $id)));
        }

        return array(
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
        );
    }

    /**
     * Deletes a Article entity.
     *
     * @Route("/{id}/delete", name="article_admin_delete")
     */
    public function deleteAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $entity = $em->getRepository('ShakyamouniSiteBundle:Article')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Article entity.');
        }

        $em->remove($entity);
        $em->flush();

        return $this->redirect($this->generateUrl('article_admin'));
    }

}

src/Shakyamouni/AdminBundle/Resources/views/ArticleAdmin/articlesBySubCategory.html.twig
{% for article in articles %}
     <li><a href="{{ path('article_admin_show', { 'id': article.id }) }}">{{ article.title }}</a></li>
{% endfor %}

src/Shakyamouni/AdminBundle/Resources/views/ArticleAdmin/edit.html.twig
{% extends "::baseAdmin.html.twig" %}

{% block body_admin %}

{% for flashMessage in app.session.flashbag.get('notice') %}
    <div class="flash-notice">
        {{ flashMessage }}
    </div>
{% endfor %}

<form action="{{ path('article_admin_update', { 'id': entity.id }) }}" method="post" {{ form_enctype(edit_form) }} novalidate>
    <div id="shakyamouni_sitebundle_articletype">
            <p>
                {{ form_label(edit_form.position, 'Position') }}
                {{ form_widget(edit_form.position, { 'attr': {'class': 'text-input small-input'} })  }} {% if form_errors(edit_form.position) %}<span class="input-notification error png_bg">{{ form_errors(edit_form.position) }}</span> {% endif %}
            </p>
        
            <p>
                {{ form_label(edit_form.subCategory, 'Sous catégorie') }}             
                {{ form_widget(edit_form.subCategory, { 'attr': {'class': 'small-input'} }) }}  {% if form_errors(edit_form.subCategory) %} <span class="input-notification error png_bg">{{ form_errors(edit_form.subCategory) }}</span> {% endif %}
            </p>
            
            <p>
                {{ form_label(edit_form.title, 'Titre') }}
                {{ form_widget(edit_form.title, { 'attr': {'class': 'text-input medium-input'} })  }} {% if form_errors(edit_form.title) %}<span class="input-notification error png_bg">{{ form_errors(edit_form.title) }}</span> {% endif %}
            </p>

            <p>
                {{ form_label(edit_form.chapo, 'Chapô') }}
                {{ form_widget(edit_form.chapo) }}
                
                {% if form_errors(edit_form.chapo) %} <br/> <span class="input-notification error png_bg">{{ form_errors(edit_form.chapo) }}</span> {% endif %}
            </p>

            <p>
                {{ form_label(edit_form.body, 'Corps du texte') }}
                {{ form_widget(edit_form.body) }}
                
                {% if form_errors(edit_form.body) %} <br/> <span class="input-notification error png_bg">{{ form_errors(edit_form.body) }}</span> {% endif %}
            </p>
            
            <p>
                {{ form_label(edit_form.isPicture, 'Y a-t-il une image principale?') }}
                {{ form_widget(edit_form.isPicture) }} {% if form_errors(edit_form.isPicture) %}<span class="input-notification error png_bg">{{ form_errors(edit_form.isPicture) }}</span> {% endif %}
            </p>

            <p>
                {{ form_label(edit_form.file, 'Image') }}
                {% if entity.picture is defined and entity.picture is not null %}
                        {% set filter_picture_size = 'thumbnail_200x200' %}
                        {% if entity.pictureSize is defined and entity.pictureSize is not null %}
                           {% set filter_picture_size = 'thumbnail_' ~ entity.pictureSize %}
                        {% endif %}
                        <p><img class="article-img" alt="{{entity.picture}}" src="{{ asset(['uploads/', entity.picture] | join | apply_filter(filter_picture_size)) }}"></p>
                    {% endif %}
                {{ form_widget(edit_form.file) }}  {% if form_errors(edit_form.file) %} <span class="input-notification error png_bg">{{ form_errors(edit_form.file) }}</span> {% endif %}
            </p>

            <p>
                {{ form_label(edit_form.pictureSize, 'Taille de l\'image') }}             
                {{ form_widget(edit_form.pictureSize, { 'attr': {'class': 'small-input'} }) }}  {% if form_errors(edit_form.pictureSize) %} <span class="input-notification error png_bg">{{ form_errors(edit_form.pictureSize) }}</span> {% endif %}
            </p>   
            
            <p>
                {{ form_label(edit_form.isVisible, 'Visible sur le site ?') }}
                (Etat Actuel: {% if entity.isVisible %}OUI{% else %}NON{% endif %})<br/>
                {{ form_widget(edit_form.isVisible) }} {% if form_errors(edit_form.isVisible) %}<span class="input-notification error png_bg">{{ form_errors(edit_form.isVisible) }}</span> {% endif %}
            </p>
    </div>

            {{ form_rest(edit_form) }}
        <p>
            <button class="button" type="submit">Mettre à jour</button>
        </p>
</form>

{{ elfinder_tinymce_init4() }}
{{ tinymce_init() }}

{% endblock %}

src/Shakyamouni/AdminBundle/Resources/views/ArticleAdmin/index.html.twig
{% extends "::baseAdmin.html.twig" %}

{% block body_admin %}

<table class="records_list">
    <thead>
        <tr>
            <th>Sous-categorie</th>
            <th>Position</th>
            <th>Titre</th>
            <th>Publié</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for entity in entities %}
            <tr>
                <td>{{ entity.subcategory }}</td>
                <td>{{ entity.position }}</td>
                <td>{{ entity.title }}</td>
                <td>{% if entity.isVisible %}OUI{% else %}NON{% endif %}</td>
                <td>
                    <a href="{{ path('article_admin_edit', { 'id': entity.id }) }}" title="Edit"><img src="{{ asset('bundles/shakyamouniadmin/images/icons/pencil.png') }}" alt="Edit" /></a>
                    <a href="{{ path('article_admin_delete', { 'id': entity.id }) }}" title="Delete" class="action-delete"><img src="{{ asset('bundles/shakyamouniadmin/images/icons/cross.png') }}" alt="Delete" /></a> 
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %} 

src/Shakyamouni/AdminBundle/Resources/views/ArticleAdmin/list.html.twig
{% for subcategory in entities %}
    <li class="li-category {%if loop.first %}no-margin-top{% endif %}"><span class="souligne">{{ subcategory.category.title|upper }}</span>/ <br/><span class="souligne-gras">{{ subcategory.title|upper }}</span></li>
    {{ render(controller('ShakyamouniAdminBundle:ArticleAdmin:articlesBySubCategory', { 'subcategory_slug': subcategory.slug })) }}
{% endfor %}

src/Shakyamouni/AdminBundle/Resources/views/ArticleAdmin/new.html.twig
{% extends "::baseAdmin.html.twig" %}

{% block body_admin %}

{% for flashMessage in app.session.flashbag.get('notice') %}
    <div class="flash-notice">
        {{ flashMessage }}
    </div>
{% endfor %}

<form action="{{ path('article_admin_create') }}" method="post" {{ form_enctype(form) }} novalidate>
    <div id="shakyamouni_sitebundle_articletype">
            <p>
                {{ form_label(form.position, 'Position') }}
                {{ form_widget(form.position, { 'attr': {'class': 'text-input small-input'} })  }} {% if form_errors(form.position) %}<span class="input-notification error png_bg">{{ form_errors(form.position) }}</span> {% endif %}
            </p>
            
            <p>
                {{ form_label(form.subCategory, 'Sous catégorie') }}             
                {{ form_widget(form.subCategory, { 'attr': {'class': 'small-input'} }) }}  {% if form_errors(form.subCategory) %} <span class="input-notification error png_bg">{{ form_errors(form.subCategory) }}</span> {% endif %}
            </p>
            
            <p>
                {{ form_label(form.title, 'Titre') }}
                {{ form_widget(form.title, { 'attr': {'class': 'text-input medium-input'} })  }} {% if form_errors(form.title) %}<span class="input-notification error png_bg">{{ form_errors(form.title) }}</span> {% endif %}
            </p>

            <p>
                {{ form_label(form.chapo, 'Chapô') }}
                {{ form_widget(form.chapo) }}
                
                {% if form_errors(form.chapo) %} <br/> <span class="input-notification error png_bg">{{ form_errors(form.chapo) }}</span> {% endif %}
            </p>

            <p>
                {{ form_label(form.body, 'Corps du texte') }}
                {{ form_widget(form.body) }}
                
                {% if form_errors(form.body) %} <br/> <span class="input-notification error png_bg">{{ form_errors(form.body) }}</span> {% endif %}
            </p>
            
            <p>
                {{ form_label(form.isPicture, 'Y a-t-il une image principale?') }}
                {{ form_widget(form.isPicture) }} {% if form_errors(form.isPicture) %}<span class="input-notification error png_bg">{{ form_errors(form.isPicture) }}</span> {% endif %}
            </p>

            <p>
                {{ form_label(form.file, 'Image') }}
                {% if entity.picture is defined and entity.picture is not null %}
                        {% set filter_picture_size = 'thumbnail_200x200' %}
                        <p><img class="article-img" alt="{{entity.picture}}" src="{{ asset(['uploads/', entity.picture] | join | apply_filter(filter_picture_size)) }}"></p>
                    {% endif %}
                {{ form_widget(form.file) }}  {% if form_errors(form.file) %} <span class="input-notification error png_bg">{{ form_errors(form.file) }}</span> {% endif %}
            </p>

            <p>
                {{ form_label(form.pictureSize, 'Taille de l\'image') }}             
                {{ form_widget(form.pictureSize, { 'attr': {'class': 'small-input'} }) }}  {% if form_errors(form.pictureSize) %} <span class="input-notification error png_bg">{{ form_errors(form.pictureSize) }}</span> {% endif %}
            </p>   
            
            <p>
                {{ form_label(form.isVisible, 'Visible sur le site ?') }}
                {{ form_widget(form.isVisible) }} {% if form_errors(form.isVisible) %}<span class="input-notification error png_bg">{{ form_errors(form.isVisible) }}</span> {% endif %}
            </p>
    </div>

            {{ form_rest(form) }}
        <p>
            <button class="button" type="submit">Créer</button>
        </p>
</form>


{{ elfinder_tinymce_init4() }}
{{ tinymce_init() }}

{% endblock %}

src/Shakyamouni/AdminBundle/Resources/views/ArticleAdmin/show.html.twig
{% extends "::baseAdmin.html.twig" %}

{% block body_admin %}

<p><span class="souligne-gras">Sous-catégorie:</span> {{ article.subCategory }}</p>
<p><span class="souligne-gras">Position:</span> {{ article.position }}</p>
<p><span class="souligne-gras">Est publié:</span> {% if article.isVisible %}OUI{% else %}NON{% endif %}</p>
{% include 'ShakyamouniSiteBundle:Commun:article.html.twig' with {'entity' : article}  %}

<table class="action-button-table">
    <tbody>
        <tr>
            <td>
                Actions possibles: <span class="edit"><a href="{{ path('article_admin_edit', { 'id': article.id }) }}" title="Edit"><img src="{{ asset('bundles/shakyamouniadmin/images/icons/pencil.png') }}" alt="Edit" /></a></span>
            </td>
            <td>
                <a href="{{ path('article_admin_delete', { 'id': article.id }) }}" title="Delete"><img src="{{ asset('bundles/shakyamouniadmin/images/icons/cross.png') }}" alt="Delete" /></a> 
            </td>
        </tr>
    </tbody>
</table>
{% endblock %} 